export default {
  SEARCH_DEBOUNCE_TIME: 300,
  SCROLL_LOAD_NEXT_DEBOUNCE_TIME: 100,
  SCROLL_OFFSET_TO_LOAD_NEW_IMAGES: 500,
  MINIMUM_SEARCH_LENGTH: 3,
  GIPHY_LIMIT: 15,
  GIPHY_API_KEY: 'XR0J5TYmEnsEjjLwzxBXwWXVjDjzTmgr',
}
